CREATE SCHEMA hospital_admissions
GO


-- Create procedures table
CREATE TABLE hospital_admissions.procedures (
    START DATETIME,
    STOP DATETIME,
    PATIENT CHAR(36),
    ENCOUNTER CHAR(36),
    CODE VARCHAR(20),
    DESCRIPTION VARCHAR(255),
    BASE_COST INT,
    REASONCODE VARCHAR(20),
    REASONDESCRIPTION VARCHAR(255),
    DURATION  FLOAT
   ) 
GO
    
-- Create encounters table
CREATE TABLE hospital_admissions.encounters (
  Id CHAR(36) PRIMARY KEY,
  START DATETIME NOT NULL,
  STOP DATETIME NOT NULL,
  PATIENT CHAR(36) NOT NULL,
  ORGANIZATION CHAR(36) NOT NULL,
  PAYER CHAR(36) NOT NULL,
  ENCOUNTERCLASS VARCHAR(50),
  CODE VARCHAR(20),
  DESCRIPTION VARCHAR(255),
  BASE_ENCOUNTER_COST REAL,
  TOTAL_CLAIM_COST REAL,
  PAYER_COVERAGE REAL,
  REASONCODE VARCHAR(20),
  REASONDESCRIPTION VARCHAR(255),
  OVER_24_HOURS INT,
  DAYS_BETWEEN_READMISSION FLOAT,
  READMISSION_30DAYS INT
)
GO


-- Create payers table
CREATE TABLE hospital_admissions.payers (
    PAYER_ID CHAR(36) PRIMARY KEY,
    NAME VARCHAR(100),
    ADDRESS VARCHAR(255),
    CITY VARCHAR(100),
    STATE_HEADQUARTERED CHAR(2),
    ZIP VARCHAR(10),
    PHONE VARCHAR(20)
)
GO

  
-- Create patients table
CREATE TABLE hospital_admissions.patients (
    Id VARCHAR(255) PRIMARY KEY,
    BIRTHDATE CHAR(4),
    DEATHDATE DATE,
    PREFIX VARCHAR(10),
    FIRST VARCHAR(100),
    LAST VARCHAR(100),
    SUFFIX VARCHAR(10),
    MAIDEN VARCHAR(100),
    MARITAL CHAR(1),
    RACE VARCHAR(50),
    ETHNICITY VARCHAR(50),
    GENDER CHAR(1),
    BIRTHPLACE VARCHAR(255),
    ADDRESS VARCHAR(255),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    COUNTY VARCHAR(100),
    ZIP VARCHAR(10)
)
GO
